spring.datasource:
  url: jdbc:mysql://localhost:3307/insurance?useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver

server.port: 8080

swagger.enabled: true
springfox.documentation.swagger.v2.path: /swagger/v2/api-docs

spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      generate-ddl: true


